export default [
  {
    files: ['server/**/*.js', 'vite.config.js'],
    languageOptions: { ecmaVersion: 'latest', sourceType: 'module',
      globals: { process: 'readonly', Buffer: 'readonly', URL: 'readonly', console: 'readonly' } },
    rules: { 'no-undef': 'error', 'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }], 'no-unreachable': 'error' },
  },
  {
    files: ['public/cms-*.js'],
    languageOptions: { ecmaVersion: 'latest', sourceType: 'module', globals: {
      window: 'readonly', document: 'readonly', sessionStorage: 'readonly', localStorage: 'readonly', location: 'readonly', fetch: 'readonly',
    } },
    rules: { 'no-undef': 'error', 'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }], 'no-unreachable': 'error' },
  },
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        Image: 'readonly',
        Event: 'readonly',
        File: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        AudioContext: 'readonly',
        webkitAudioContext: 'readonly',
        createImageBitmap: 'readonly',
        requestAnimationFrame: 'readonly',
        getComputedStyle: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        alert: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
      'no-undef': 'error',
      'no-dupe-keys': 'error',
      'no-dupe-args': 'error',
      'no-unreachable': 'error',
      'no-cond-assign': 'error',
      'no-constant-condition': 'warn',
      'no-fallthrough': 'error',
      'no-redeclare': 'error',
      'no-self-assign': 'error',
      'no-irregular-whitespace': 'warn',
    },
  },
  {
    files: ['test/**/*.js'],
    languageOptions: { ecmaVersion: 'latest', sourceType: 'module' },
  },
];
