/* Original iPhone-inspired artwork. See public/emoji/iphone-inspired/README.md. */
export const EMOJI_CATEGORIES = [
  {"id":"faces","label":"Ekspresi","en":"Faces"},
  {"id":"hearts","label":"Hati","en":"Hearts"},
  {"id":"hands","label":"Tangan","en":"Hands"},
  {"id":"nature","label":"Hewan & Alam","en":"Animals & Nature"},
  {"id":"food","label":"Makanan","en":"Food"},
  {"id":"party","label":"Pesta & Benda","en":"Party & Objects"},
];

export const EMOJI_CATALOG = [
  {"value":"😀","category":"faces","index":0,"name":"Grinning face","keywords":"senyum lebar"},
  {"value":"😃","category":"faces","index":1,"name":"Grinning face with big eyes","keywords":"senyum mata besar"},
  {"value":"😄","category":"faces","index":2,"name":"Grinning face with smiling eyes","keywords":"senyum bahagia"},
  {"value":"😁","category":"faces","index":3,"name":"Beaming grin with teeth","keywords":"senyum gigi"},
  {"value":"😆","category":"faces","index":4,"name":"Laughing squinting face","keywords":"tertawa"},
  {"value":"😅","category":"faces","index":5,"name":"Smiling face with sweat","keywords":"keringat"},
  {"value":"😂","category":"faces","index":6,"name":"Face with tears of joy","keywords":"ngakak ketawa"},
  {"value":"🙂","category":"faces","index":7,"name":"Slight smile","keywords":"senyum kecil"},
  {"value":"🙃","category":"faces","index":8,"name":"Upside-down smile","keywords":"terbalik"},
  {"value":"😉","category":"faces","index":9,"name":"Winking face","keywords":"kedip"},
  {"value":"😊","category":"faces","index":10,"name":"Smiling face with rosy cheeks","keywords":"malu pipi merah"},
  {"value":"😍","category":"faces","index":11,"name":"Heart eyes","keywords":"mata hati cinta"},
  {"value":"🥰","category":"faces","index":12,"name":"Smiling face with three hearts","keywords":"sayang cinta"},
  {"value":"😘","category":"faces","index":13,"name":"Blowing a kiss","keywords":"cium"},
  {"value":"😎","category":"faces","index":14,"name":"Face with sunglasses","keywords":"keren kacamata"},
  {"value":"🥹","category":"faces","index":15,"name":"Face holding back tears","keywords":"terharu"},
  {"value":"😭","category":"faces","index":16,"name":"Loudly crying face","keywords":"nangis sedih"},
  {"value":"😴","category":"faces","index":17,"name":"Sleeping face","keywords":"tidur"},
  {"value":"🤔","category":"faces","index":18,"name":"Thinking face","keywords":"berpikir"},
  {"value":"🤩","category":"faces","index":19,"name":"Star eyes","keywords":"mata bintang"},
  {"value":"❤️","category":"hearts","index":0,"name":"Red heart","keywords":"hati merah cinta"},
  {"value":"🧡","category":"hearts","index":1,"name":"Orange heart","keywords":"hati oranye"},
  {"value":"💛","category":"hearts","index":2,"name":"Yellow heart","keywords":"hati kuning"},
  {"value":"💚","category":"hearts","index":3,"name":"Green heart","keywords":"hati hijau"},
  {"value":"💙","category":"hearts","index":4,"name":"Blue heart","keywords":"hati biru"},
  {"value":"💜","category":"hearts","index":5,"name":"Purple heart","keywords":"hati ungu"},
  {"value":"🖤","category":"hearts","index":6,"name":"Black heart","keywords":"hati hitam"},
  {"value":"🤍","category":"hearts","index":7,"name":"White heart","keywords":"hati putih"},
  {"value":"🤎","category":"hearts","index":8,"name":"Brown heart","keywords":"hati cokelat"},
  {"value":"🩷","category":"hearts","index":9,"name":"Pink heart","keywords":"hati pink merah muda"},
  {"value":"🩵","category":"hearts","index":10,"name":"Light blue heart","keywords":"hati biru muda"},
  {"value":"🩶","category":"hearts","index":11,"name":"Grey heart","keywords":"hati abu"},
  {"value":"💖","category":"hearts","index":12,"name":"Sparkling heart","keywords":"hati berkilau"},
  {"value":"💗","category":"hearts","index":13,"name":"Growing heart with two nested outlines","keywords":"hati membesar"},
  {"value":"💓","category":"hearts","index":14,"name":"Beating heart with motion lines","keywords":"hati berdebar"},
  {"value":"💕","category":"hearts","index":15,"name":"Two pink hearts","keywords":"dua hati"},
  {"value":"💞","category":"hearts","index":16,"name":"Revolving pink hearts","keywords":"hati berputar"},
  {"value":"💘","category":"hearts","index":17,"name":"Heart with arrow","keywords":"panah cinta"},
  {"value":"💔","category":"hearts","index":18,"name":"Broken heart","keywords":"patah hati"},
  {"value":"💋","category":"hearts","index":19,"name":"Red lipstick kiss mark","keywords":"bibir cium"},
  {"value":"👍","category":"hands","index":0,"name":"Thumbs up","keywords":"jempol bagus"},
  {"value":"👎","category":"hands","index":1,"name":"Thumbs down","keywords":"jempol turun"},
  {"value":"👏","category":"hands","index":2,"name":"Clapping hands","keywords":"tepuk tangan"},
  {"value":"🙌","category":"hands","index":3,"name":"Both hands raised in celebration","keywords":"hore angkat tangan"},
  {"value":"👐","category":"hands","index":4,"name":"Two open hands facing viewer","keywords":"tangan terbuka"},
  {"value":"🤲","category":"hands","index":5,"name":"Two cupped hands held together","keywords":"menadah"},
  {"value":"🙏","category":"hands","index":6,"name":"Folded praying hands","keywords":"doa terima kasih"},
  {"value":"🤝","category":"hands","index":7,"name":"Handshake","keywords":"salaman"},
  {"value":"💪","category":"hands","index":8,"name":"Flexed bicep","keywords":"otot semangat"},
  {"value":"👋","category":"hands","index":9,"name":"Waving hand","keywords":"dadah halo"},
  {"value":"🤚","category":"hands","index":10,"name":"Raised back of hand","keywords":"punggung tangan"},
  {"value":"✋","category":"hands","index":11,"name":"Raised palm with joined fingers","keywords":"stop telapak"},
  {"value":"🖐️","category":"hands","index":12,"name":"Hand with spread fingers","keywords":"lima jari"},
  {"value":"👌","category":"hands","index":13,"name":"OK hand circle","keywords":"oke"},
  {"value":"🤌","category":"hands","index":14,"name":"Pinched fingers pointing up","keywords":"jari kuncup"},
  {"value":"🤏","category":"hands","index":15,"name":"Pinching hand with small gap","keywords":"sedikit"},
  {"value":"✌️","category":"hands","index":16,"name":"Victory peace hand","keywords":"peace damai"},
  {"value":"🤞","category":"hands","index":17,"name":"Crossed index and middle fingers","keywords":"semoga beruntung"},
  {"value":"🤟","category":"hands","index":18,"name":"Love-you hand gesture with thumb index and little finger raised","keywords":"aku cinta kamu"},
  {"value":"🫶","category":"hands","index":19,"name":"Two hands forming a heart","keywords":"hati tangan"},
  {"value":"🐱","category":"nature","index":0,"name":"Cat face","keywords":"kucing"},
  {"value":"🐰","category":"nature","index":1,"name":"Rabbit face","keywords":"kelinci"},
  {"value":"🐻","category":"nature","index":2,"name":"Bear face","keywords":"beruang"},
  {"value":"🐥","category":"nature","index":3,"name":"Front-facing baby chick","keywords":"anak ayam"},
  {"value":"🐶","category":"nature","index":4,"name":"Dog face","keywords":"anjing"},
  {"value":"🐼","category":"nature","index":5,"name":"Panda face","keywords":"panda"},
  {"value":"🦊","category":"nature","index":6,"name":"Fox face","keywords":"rubah"},
  {"value":"🐸","category":"nature","index":7,"name":"Frog face","keywords":"katak"},
  {"value":"🦋","category":"nature","index":8,"name":"Butterfly","keywords":"kupu-kupu"},
  {"value":"🐾","category":"nature","index":9,"name":"Paw prints","keywords":"jejak kaki"},
  {"value":"🌸","category":"nature","index":10,"name":"Cherry blossom","keywords":"sakura bunga"},
  {"value":"🌺","category":"nature","index":11,"name":"Hibiscus","keywords":"kembang sepatu"},
  {"value":"🌻","category":"nature","index":12,"name":"Sunflower","keywords":"bunga matahari"},
  {"value":"🌹","category":"nature","index":13,"name":"Red rose","keywords":"mawar"},
  {"value":"🍀","category":"nature","index":14,"name":"Four-leaf clover","keywords":"semanggi keberuntungan"},
  {"value":"🌈","category":"nature","index":15,"name":"Rainbow","keywords":"pelangi"},
  {"value":"☀️","category":"nature","index":16,"name":"Sun with rays","keywords":"matahari"},
  {"value":"🌙","category":"nature","index":17,"name":"Crescent moon","keywords":"bulan"},
  {"value":"⭐","category":"nature","index":18,"name":"Gold star","keywords":"bintang"},
  {"value":"🌟","category":"nature","index":19,"name":"Glowing star with small rays","keywords":"bintang bersinar"},
  {"value":"🍒","category":"food","index":0,"name":"Pair of cherries","keywords":"ceri"},
  {"value":"🍕","category":"food","index":1,"name":"Pizza slice","keywords":"pizza"},
  {"value":"🍿","category":"food","index":2,"name":"Popcorn carton","keywords":"popcorn berondong"},
  {"value":"🥑","category":"food","index":3,"name":"Avocado half","keywords":"alpukat"},
  {"value":"🍓","category":"food","index":4,"name":"Strawberry","keywords":"stroberi"},
  {"value":"🧁","category":"food","index":5,"name":"Cupcake","keywords":"cupcake kue"},
  {"value":"🍦","category":"food","index":6,"name":"Soft ice cream cone","keywords":"es krim"},
  {"value":"🍩","category":"food","index":7,"name":"Pink glazed doughnut","keywords":"donat"},
  {"value":"🍪","category":"food","index":8,"name":"Chocolate chip cookie","keywords":"kukis biskuit"},
  {"value":"🍰","category":"food","index":9,"name":"Strawberry shortcake slice","keywords":"kue potong"},
  {"value":"🍔","category":"food","index":10,"name":"Hamburger","keywords":"burger"},
  {"value":"🍟","category":"food","index":11,"name":"French fries carton","keywords":"kentang goreng"},
  {"value":"🌮","category":"food","index":12,"name":"Taco","keywords":"taco"},
  {"value":"🍣","category":"food","index":13,"name":"Salmon sushi","keywords":"sushi"},
  {"value":"🍜","category":"food","index":14,"name":"Bowl of ramen with chopsticks","keywords":"mi ramen"},
  {"value":"🍉","category":"food","index":15,"name":"Watermelon slice","keywords":"semangka"},
  {"value":"🍋","category":"food","index":16,"name":"Lemon","keywords":"lemon"},
  {"value":"🍇","category":"food","index":17,"name":"Purple grapes","keywords":"anggur"},
  {"value":"🧋","category":"food","index":18,"name":"Bubble tea cup","keywords":"boba teh susu"},
  {"value":"☕","category":"food","index":19,"name":"Hot coffee cup","keywords":"kopi"},
  {"value":"✨","category":"party","index":0,"name":"Three golden sparkles","keywords":"kilau"},
  {"value":"🎀","category":"party","index":1,"name":"Pink ribbon bow","keywords":"pita"},
  {"value":"👑","category":"party","index":2,"name":"Golden crown","keywords":"mahkota"},
  {"value":"🕶️","category":"party","index":3,"name":"Black sunglasses","keywords":"kacamata hitam"},
  {"value":"⚡","category":"party","index":4,"name":"Yellow lightning bolt","keywords":"petir"},
  {"value":"🎈","category":"party","index":5,"name":"Red balloon on string","keywords":"balon"},
  {"value":"🎉","category":"party","index":6,"name":"Party popper with confetti","keywords":"pesta perayaan"},
  {"value":"💬","category":"party","index":7,"name":"White speech bubble with three dots","keywords":"pesan percakapan"},
  {"value":"💌","category":"party","index":8,"name":"Love letter envelope with heart","keywords":"surat cinta"},
  {"value":"🧸","category":"party","index":9,"name":"Teddy bear","keywords":"boneka beruang"},
  {"value":"🎊","category":"party","index":10,"name":"Confetti ball","keywords":"konfeti"},
  {"value":"🎁","category":"party","index":11,"name":"Wrapped gift","keywords":"kado hadiah"},
  {"value":"🎂","category":"party","index":12,"name":"Birthday cake with candles","keywords":"ulang tahun kue"},
  {"value":"🪩","category":"party","index":13,"name":"Silver disco ball","keywords":"disko"},
  {"value":"🎵","category":"party","index":14,"name":"Musical eighth note","keywords":"musik nada"},
  {"value":"📷","category":"party","index":15,"name":"Camera","keywords":"kamera foto"},
  {"value":"🕯️","category":"party","index":16,"name":"Lit candle","keywords":"lilin"},
  {"value":"🫧","category":"party","index":17,"name":"Three soap bubbles","keywords":"gelembung"},
  {"value":"🏆","category":"party","index":18,"name":"Golden trophy","keywords":"piala juara"},
  {"value":"🔥","category":"party","index":19,"name":"Orange red fire flame","keywords":"api"},
];

export function findEmojiStickers(query = '', category = 'all') {
  const words = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  return EMOJI_CATALOG.filter(entry =>
    (category === 'all' || entry.category === category) &&
    words.every(word => (entry.value + ' ' + entry.name + ' ' + entry.keywords)
      .toLocaleLowerCase().includes(word))
  );
}

